Adding def_enable, platform_map, and custom_data_source options
CiscoTestAutomation/pyats.contrib pull request #57
Opened 2022-02-02 17:14 UTC by jeremypng

Add the following parameters to the netbox creator:

* def_enable
* platform_map
* custom_data_source

The def_enable is what you would expect. It adds whatever is provided as the enable password in the testbed credentials.

The platform map and custom_data_source take the following form:
```python
                platform_map = {
                    "dnac": {
                        "platform": "switch",
                        "os": "iosxe"
                    },
                    "vmanage": {
                        "platform": "sdwan",
                        "os": "iosxe"
                    }
                },
                custom_data_source = [
                    "config_context",
                    "pyats_custom"
                ]
```

The platform_map allows you to take whatever you have in Netbox for Platform and map it to a particular platform and os setting in PyATS. If it is not provided or matched, it follows the current processing for platform and os determination.

The custom_data_source will lookup whatever is provided in the list recursively using the self._get_info that is already in the netbox creator. That value will be set as the custom key in the testbed for the device.

2022-02-07 17:08 UTC, LukasMcClelland requested changes
Looks good, thank you for including an explanation of your changes in the class docstring

Please also include a changelog in the following directory
```
https://github.com/CiscoTestAutomation/pyats.contrib/tree/master/docs/changelog/undistributed
```

2022-02-07 17:08 UTC, LukasMcClelland commented on src/pyats/contrib/creators/netbox.py
> +            if platform_map_success == False:
I think a small comment here to mention that this is default behavior would be useful for future reference. Something kinda like (please adjust to your liking):
```suggestion
            # If platform mapping was not provided or was unsuccessful, then default to standard behavior for assigning os and platform
            if platform_map_success == False:
```

2022-02-08 23:04 UTC, jeremypng commented
I added the suggested comment and the changelog. Let me know if there is anything else. Thanks!

2022-02-09 20:16 UTC, danielgraziano approved these changes

2022-03-11 21:06 UTC, merged