Fix gathering data if keys are not defined
CiscoTestAutomation/pyats.contrib pull request #65
Opened 2022-05-31 06:23 UTC by Kani999

Close #64

2022-06-10 20:51 UTC, domachad commented
Hi @Kani999, thank you for your contribution. Would it be possible for you to add a unit test that covers this fix?

2022-06-14 09:51 UTC, Kani999 commented
> Hi @Kani999, thank you for your contribution. Would it be possible for you to add a unit test that covers this fix?

Hello @domachad,
I don't know how to add some tests. It should create some docker instance of Netbox, to create a `Netbox (TextbedCreator)` connection or something like that? 

Because in [pyats.contrib](https://github.com/CiscoTestAutomation/pyats.contrib)/[src](https://github.com/CiscoTestAutomation/pyats.contrib/tree/master/src)/[pyats](https://github.com/CiscoTestAutomation/pyats.contrib/tree/master/src/pyats)/[contrib](https://github.com/CiscoTestAutomation/pyats.contrib/tree/master/src/pyats/contrib)/[creators](https://github.com/CiscoTestAutomation/pyats.contrib/tree/master/src/pyats/contrib/creators)/[tests](https://github.com/CiscoTestAutomation/pyats.contrib/tree/master/src/pyats/contrib/creators/tests)/test_netbox.py file I'll create a test:

```
    def test_generate_testbed(self):
        with self.assertRaises(Exception):
            netbox_testbed_creator = Netbox(user_token="abc", netbox_url="abc", custom_data_source=[])
            netbox_testbed_creator._generate() # This fails, because URL is invalid, so I could not test inner functionality
```

2022-06-15 09:44 UTC, Kani999 commented
@domachad I've created a "proof of concept" branch which adds the unit test. The branch require `pytest-docker` installed via pip and installed `docker` at the machine. 

There's a comparation of changes:
   - https://github.com/CiscoTestAutomation/pyats.contrib/compare/master...Kani999:fix_netbox_testbed_creator_with_docker_tests?expand=1

2022-06-15 21:24 UTC, domachad commented
> @domachad I've created a "proof of concept" branch which adds the unit test. The branch require `pytest-docker` installed via pip and installed `docker` at the machine.
> 
> There's a comparation of changes:
> 
> * https://github.com/CiscoTestAutomation/pyats.contrib/compare/master...Kani999:fix_netbox_testbed_creator_with_docker_tests?expand=1

We avoid adding dependencies whenever possible. I believe you should be able to mock the class and/or methods you might need to call. The point of adding the UT is to have as much code coverage as we can. If anybody makes any changes that might break our code, then we will be able to check that before we merge it.

2022-06-16 06:46 UTC, Kani999 commented
@domachad  So if I want to call method [_generate()](https://github.com/CiscoTestAutomation/pyats.contrib/pull/65) I have to mock data which is returned by calling multiple API endpoints. 
I'll try to look at it, but I've never written a test like this.

2022-06-16 10:17 UTC, Kani999 commented
@domachad I've added a unit test which mocks the API calls that are called in `_generate()` method. 
It needs to install package `responses`. I did not find any `requirements_dev.txt` or any development packages in the setup. Where should be the dependency included?

2022-07-05 15:15 UTC, domachad requested changes

2022-07-11 10:19 UTC, Kani999 commented
> @Kani999 Thank you for your contribution. Unit tests are failing, can you please fix that?

@ademz Unit tests are fixed. Can you run the CI?

2022-07-11 10:21 UTC, Kani999 commented on src/pyats/contrib/creators/tests/test_netbox.py
> +
@domachad I've applied your changes. Thank you

2022-07-11 15:47 UTC, domachad approved these changes

2022-07-11 18:32 UTC, merged